[features]
seeds = true
skip-lint = false
[programs.localnet]
anchor_nft_staking = "4zfgQUQgTaHAyEi8c1tzzcorrvLPqEB6ZdJpg4t9dZBP"
lootbox_program = "5942mns31g8zYvepfHb8TBSzGktZwyXXekwGkfNrE2u6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/blockfather/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
